name: CI/CD Pipeline

# Trigger on push to main and on pull requests targeting main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      # Docker Hub username stored in repo secrets
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test || echo "No tests found"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image (push only from main)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' }}
          platforms: linux/amd64
          tags: |
            ${{ env.IMAGE_NAME }}/devops-pipeline-project:latest
            ${{ env.IMAGE_NAME }}/devops-pipeline-project:${{ github.sha }}
            # duplicate block removed

